### ISSUE TITLE
Wrong Postgres Version on Travis/Ubuntu

### ISSUE THREAD

**Issue by msom** [OneGov/onegov_testing#2]
Some travis images have multiple versions of Postgres installed which may result in `testing.postgres` picking the wrong version (it searches in `/usr/lib/postgresql` and picks the first one found).

For the moment, I pinned it to 9.6 with 959d8e755bb8f3f2162b3cf833f30a50b6e54216 but we should probably solve this in a cleaner way - such as adding an option to `testing.postgres.Postgresql` to provide a list of preferred versions.

**Comment by msom** [comment]
@href any thoughts on this?

**Comment by href** [comment]
I'm okay with passing a list of preferred versions and picking the first one that can be found. We can't really pin to the actual version we need since Travis doesn't support Postgres 10 yet.
